# Generated by Django 3.1.3 on 2020-11-25 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomChapitre', models.CharField(max_length=20)),
                ('DateCreationChapitre', models.DateTimeField(auto_now_add=True)),
                ('Cours', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academy.cours')),
            ],
        ),
    ]
