# Generated by Django 3.1.3 on 2020-11-25 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_chapitre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('PwdEnseignant', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomEtudiant', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('Pwd', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='chapitre',
            name='ContenusChapitre',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cours',
            name='NombreChapitre',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='cours',
            name='titre',
            field=models.CharField(default='securité', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='NomChapitre',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chemin', models.TextField(default='')),
                ('Nomvideos', models.CharField(max_length=250)),
                ('IdCours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.cours')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContenusQuiz', models.TextField(default='')),
                ('IdChapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.chapitre')),
            ],
        ),
    ]
