# Generated by Django 3.1.3 on 2020-11-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_auto_20201125_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='Chemin',
        ),
        migrations.AddField(
            model_name='videos',
            name='file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
