# Generated by Django 3.1.3 on 2020-11-25 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_auto_20201125_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='NomCours',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='academy.cours'),
            preserve_default=False,
        ),
    ]
