# Generated by Django 3.1.3 on 2020-11-25 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_auto_20201125_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='NomCours',
        ),
    ]
