# Generated by Django 3.1.3 on 2020-11-25 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_enseignant_nomcours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='NomCours',
        ),
    ]
