# Generated by Django 3.1.3 on 2020-11-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_remove_enseignant_nomcours'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='NomQuiz',
            field=models.CharField(default='', max_length=255),
        ),
    ]
