# Generated by Django 3.1.3 on 2020-11-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_quiz_nomquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='PhotoEnseignant',
            field=models.ImageField(default='image.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='PhotoEtudiant',
            field=models.ImageField(default='image.png', upload_to=''),
        ),
    ]
