# Generated by Django 3.1.3 on 2020-11-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0011_auto_20201125_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='PhotoCours',
            field=models.ImageField(default='image.png', upload_to=''),
        ),
    ]
