# Generated by Django 3.1.3 on 2020-11-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0013_cours_nomenseignant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='DateCreationCours',
            field=models.DateField(auto_now_add=True),
        ),
    ]
