# Generated by Django 3.1.3 on 2020-11-25 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0016_cours_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contenus', models.CharField(default='', max_length=250)),
                ('DatePublication', models.DateField(auto_now_add=True)),
                ('Etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.etudiant')),
            ],
        ),
    ]
