# Generated by Django 3.1.3 on 2020-12-05 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0018_auto_20201205_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='titre',
        ),
    ]
