# Generated by Django 3.1.3 on 2020-12-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0019_remove_cours_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='description',
            field=models.TextField(default='cours'),
        ),
    ]
