# Generated by Django 3.1.3 on 2020-12-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0020_auto_20201205_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
