# Generated by Django 3.1.3 on 2020-12-06 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0021_auto_20201205_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onligne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCours', models.DateTimeField(auto_now=True)),
                ('NomGroupe', models.CharField(blank=True, max_length=150)),
                ('NomCours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.cours')),
                ('NomEnseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.enseignant')),
            ],
        ),
    ]
