# Generated by Django 3.1.3 on 2020-12-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0022_onligne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onligne',
            name='DateCours',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
